Prevent CLI from throwing errors altogether.
The issue I was having was that if I ran `node server.js status`, I would get
this error:
```
./node_modules/clu/lib/commandLine.js:209
	else throw err;
	           ^
Error: connect ENOENT
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)
```

I haven't been able to figure out how to directly execute the status command,
and thus, haven't been able to add a proper test.  Any help here would be
greatly appreciated.